# Generated by Django 2.1.3 on 2019-04-18 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_B', models.DateTimeField(blank=True)),
                ('coste_B', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(default='Ingrese Nombre', max_length=200)),
                ('apellido', models.CharField(default='Ingrese Apellido', max_length=200)),
                ('cedula', models.IntegerField(default=20000)),
                ('email', models.EmailField(default='ejemplo@go.com', max_length=254)),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField(unique=True)),
                ('confirmacion', models.BooleanField(blank=True, null=True)),
                ('f_envio', models.DateTimeField(blank=True, null=True)),
                ('Num_Bolsa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro1.Bolsa')),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prod_Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_prod', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('Num_prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registro1.prod_Bolsa')),
                ('nombre', models.CharField(default='Ingrese Producto', max_length=200)),
                ('precio', models.IntegerField(default=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prod_bolsa',
            name='Num_Bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro1.Bolsa'),
        ),
        migrations.AddField(
            model_name='prod_bolsa',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
