# Generated by Django 2.1.3 on 2019-04-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='banc',
            field=models.CharField(default='ninguno', max_length=200),
            preserve_default=False,
        ),
    ]
