# Generated by Django 2.1.3 on 2019-04-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0002_pagos_banc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='banc',
        ),
        migrations.AddField(
            model_name='pagos',
            name='banco',
            field=models.CharField(default='Venezuela', max_length=200),
            preserve_default=False,
        ),
    ]
