# Generated by Django 2.1.3 on 2018-11-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0003_auto_20181121_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
