# Generated by Django 2.2.2 on 2019-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0003_bolsa_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.CharField(max_length=2000000),
        ),
    ]
