# Generated by Django 2.1.3 on 2019-01-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0004_auto_20181121_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
            ],
        ),
    ]
