# Generated by Django 2.1.3 on 2019-01-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
