# Generated by Django 2.1.3 on 2019-01-21 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro1', '0006_auto_20190112_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('cedula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ingresar',
        ),
        migrations.DeleteModel(
            name='Login1',
        ),
    ]
