# Generated by Django 2.1.3 on 2019-01-25 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0008_datos_fedicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='id',
        ),
        migrations.AlterField(
            model_name='datos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
