# Generated by Django 2.1.3 on 2019-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0011_auto_20190127_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datos',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
