# Generated by Django 2.1.3 on 2019-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0012_auto_20190128_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='apellido',
            field=models.CharField(default='Ingrese Apellido', max_length=200),
        ),
        migrations.AlterField(
            model_name='datos',
            name='nombre',
            field=models.CharField(default='Ingrese Nombre', max_length=200),
        ),
    ]
