# Generated by Django 2.1.3 on 2019-01-28 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0014_auto_20190128_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='dingreso',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
