# Generated by Django 2.1.3 on 2019-01-28 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0017_auto_20190128_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='dingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datos',
            name='fedicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
