# Generated by Django 2.1.3 on 2019-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0020_auto_20190128_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.IntegerField(default=20000),
        ),
    ]
