# Generated by Django 2.1.3 on 2019-02-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0021_auto_20190128_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_B', models.DateTimeField(blank=True)),
                ('coste_B', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='prod_Bolsa',
            fields=[
                ('Num_Bolsa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registro1.Bolsa')),
                ('id_prod', models.IntegerField(unique=True)),
                ('cant_prod', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('Num_prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registro1.prod_Bolsa')),
                ('nombre', models.CharField(default='Ingrese Producto', max_length=200)),
                ('precio', models.IntegerField(default=100)),
            ],
        ),
    ]
