# Generated by Django 2.1.3 on 2019-02-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro1', '0023_auto_20190225_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_bolsa',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prod_bolsa',
            name='Num_Bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro1.Bolsa'),
        ),
    ]
